language: node_js
node_js: 
  - "12"
services:
  - docker
before_install:
  - docker pull debricked/debricked-cli
script:
  - docker run -it --rm -v -e $PWD:/data debricked/debricked-cli debricked:scan USERNAME="" PASSWORD=${DEBRICKED_TOKEN} repository_name=${REPOSITORY} commit_name=${COMMIT} null cli
